### ISSUE TITLE
smerge

### ISSUE THREAD

**Issue by jwillikers** [snapcrafters/sublime-merge#1]
Would it be possible to provide the standard `smerge` alias for SublimeMerge? It is described [here](https://www.sublimemerge.com/docs/command_line).

**Comment by shukerov** [comment]
A temporary workaround to this might be to use a manual snap alias. You can create one by running:

`sudo snap alias sublime-merge smerge`

Read more about *commands and aliases*  [here](https://snapcraft.io/docs/commands-and-aliases).

**Comment by rojosinalma** [comment]
Any chances this can be provided out of the box without having to create an alias?

**Comment by jwillikers** [comment]
@rojosinalma Yes, though this requires acceptance through Snapcraft. I've opened a request for this alias [here](https://forum.snapcraft.io/t/request-for-sublime-merge-alias-smerge/21425?u=jwillikers).

**Comment by jwillikers** [comment]
The `smerge` alias has been added in commit d0734f1.
