### ISSUE TITLE
[Bug]: Snap won't work without git installed locally

### ISSUE THREAD

**Issue by soumyaDghosh** [snapcrafters/sublime-merge#19]
### What happened?

The app will not work unless and until I have installed git in my local machine.

### What should have happened?

As a snap package, it should not be depending on local file/libraries for git.

### Output of `snap info $snap_name`

```shell
name:      sublime-merge
summary:   Meet a new Git Client, from the makers of Sublime Text
publisher: Snapcrafters✪
store-url: https://snapcraft.io/sublime-merge
contact:   https://github.com/snapcrafters/sublime-merge/issues
license:   unset
description: |
  Meet a new Git Client, from the makers of Sublime Text.
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - sublime-merge
snap-id:      tDX7iejihNrsIdo8vfrxUZ3t4x7fO9VT
tracking:     latest/stable
refresh-date: today at 20:25 IST
channels:
  latest/stable:    2091 2023-10-11 (38) 70MB classic
  latest/candidate: ↑                         
  latest/beta:      2091 2023-10-11 (38) 70MB classic
  latest/edge:      2091 2023-12-06 (40) 70MB classic
installed:          2091            (38) 70MB classic
```

### Output of `snap connections $snap_name`

```shell
Classic snap is not showing it
```

### Output of `snap version`

```shell
snap    2.60.4+23.10.1
snapd   2.60.4+23.10.1
series  16
ubuntu  23.10
kernel  6.5.0-13-generic
```

**Comment by popey** [comment]
I'm conflicted about this. While I agree it's helpful to have whatever the application needs, in order to work, nobody has ever reported this as a problem for the last four years, and there's nearly 8K users. Sublime Merge is very much a developer tool, and I'd expect most developers these days have git installed, or it ships by default.

Keen to hear other points of view though.

**Comment by merlijn-sebrechts** [comment]
I agree with Popey. Additionally, distributions make sure their git package integrates perfectly into the desktop environment, with keyrings and SSH agents. Making sure our git does the same thing will take considerable work for almost no gain.

**Comment by jnsgruk** [comment]
Yeh, I think I agree with @merlijn-sebrechts and @popey here.

**Comment by merlijn-sebrechts** [comment]
Closing this as I think we've reached agreement that it's better to use host git.
