### ISSUE TITLE
[Enhancement]: Update to 2068?

### ISSUE THREAD

**Issue by ryanpcmcquen** [snapcrafters/sublime-merge#8]
### What changes would you like?

Update to 2068?

**Comment by zyga** [comment]
I've just bumped to 2071, build is in progress.

**Comment by zyga** [comment]
2071 is now live in stable

**Comment by jonas-sfx** [comment]
or just update to [2074](https://github.com/snapcrafters/sublime-merge/pull/10) ?

**Comment by diddledani** [comment]
2079 is merged and available in edge
